# Generated by Django 6.0.2 on 2026-03-02 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField(max_length=30)),
                ('categoria', models.CharField(choices=[('P', 'Pullover'), ('J', 'Jarra')], max_length=5)),
                ('tipo', models.CharField(choices=[('Per', 'Personalizado'), ('E', 'Estandar')], max_length=5)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=30)),
                ('estado', models.IntegerField(choices=[('R', 'En camino'), ('L', 'Listo'), ('D', 'Demorado')], max_length=5)),
                ('metodo_pago', models.CharField(blank=True, max_length=30)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercancia.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(blank=True, max_length=30)),
                ('telefono', models.IntegerField(max_length=10)),
                ('direccion', models.CharField(max_length=30)),
                ('metodo_pago', models.CharField(blank=True, max_length=30)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercancia.pedido')),
            ],
        ),
    ]
