# Generated by Django 6.0.2 on 2026-03-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercancia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
