# Generated by Django 6.0.2 on 2026-03-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercancia', '0002_alter_pedido_estado_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
