# Generated by Django 6.0.2 on 2026-03-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercancia', '0004_pedidoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='pedido_id',
        ),
    ]
