# Generated by Django 6.0.2 on 2026-03-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercancia', '0006_remove_usuario_pedido_pedido_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='numero_pedido',
        ),
    ]
