# Generated by Django 6.0.2 on 2026-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercancia', '0007_alter_pedido_options_remove_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='fecha_y_hora_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('C', 'Carrito'), ('P', 'Pagado'), ('R', 'Enviado'), ('E', 'Entregado'), ('C', 'Cancelado')], max_length=1),
        ),
    ]
