# Generated by Django 6.0.2 on 2026-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercancia', '0008_pedidoitem_actualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='actualizacion',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='fecha_y_hora_creacion',
        ),
        migrations.AddField(
            model_name='pedido',
            name='actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_y_hora_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencia_envio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
